# Generated by Django 2.1.7 on 2019-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('user_pwd', models.CharField(max_length=256)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['user_c_time'],
            },
        ),
    ]
