# Generated by Django 2.1.7 on 2019-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(max_length=128)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('deadline_date', models.DateField()),
            ],
        ),
    ]
