# Generated by Django 2.1.7 on 2019-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Notes',
        ),
    ]
