# Generated by Django 2.1.7 on 2019-06-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_owner',
            field=models.CharField(max_length=128),
        ),
    ]
