# Generated by Django 2.1.7 on 2019-06-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20190606_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_fp',
            field=models.CharField(default='<django.db.models.fields.CharField><django.db.models.fields.CharField>', max_length=383),
        ),
    ]
