# Generated by Django 2.1.7 on 2019-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_score_score_fp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_fp',
            field=models.CharField(max_length=383),
        ),
    ]
