# Generated by Django 2.1.7 on 2019-06-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20190606_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_fp',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
