# Generated by Django 2.1.7 on 2019-03-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
