# Generated by Django 2.1.7 on 2019-03-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesystem', '0002_delete_filemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='upload')),
                ('file_name', models.CharField(max_length=256)),
                ('file_owner', models.CharField(max_length=256)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
