# Generated by Django 2.1.7 on 2019-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0003_filemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
