# Generated by Django 2.1.7 on 2019-04-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0004_auto_20190407_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_Attribution',
            field=models.CharField(default='第六章456789', max_length=255),
        ),
    ]
