# Generated by Django 2.1.7 on 2019-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0005_filemodel_file_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_Attribution',
            field=models.CharField(max_length=255),
        ),
    ]
