# Generated by Django 2.1.7 on 2019-04-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesystem', '0006_auto_20190411_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file_Attribution',
            new_name='file_attribution',
        ),
    ]
